# Generated by Django 5.2.13 on 2026-04-18 21:46

from collections import defaultdict

from django.db import migrations, models


def _normalize_email(value):
    return (value or '').strip().lower()


def deduplicate_emails_before_unique_constraint(apps, schema_editor):
    """
    Garantit des e-mails non vides et uniques (insensible à la casse)
    avant la contrainte SQL unique.
    """
    User = apps.get_model('users', 'User')

    for user in User.objects.all().order_by('pk'):
        if not _normalize_email(user.email):
            user.email = f'{user.username}@import.invalid'
            user.save(update_fields=['email'])

    groups = defaultdict(list)
    for user in User.objects.all().order_by('pk'):
        groups[_normalize_email(user.email)].append(user)

    for _key, users in groups.items():
        if len(users) <= 1:
            continue
        for u in users[1:]:
            local, sep, domain = u.email.partition('@')
            if not sep:
                u.email = f'{u.username}@import.invalid'
            else:
                u.email = f'{local}+user{u.pk}@{domain}'
            u.save(update_fields=['email'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            deduplicate_emails_before_unique_constraint,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                blank=True,
                max_length=254,
                unique=True,
                verbose_name='adresse e-mail',
            ),
        ),
    ]
