# Generated by Django 5.2.13 on 2026-04-18 20:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField(help_text='Minimum 20 caractères.', validators=[django.core.validators.MinLengthValidator(20)], verbose_name='motivation')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Refusée')], default='pending', max_length=20, verbose_name='statut')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='date de candidature')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_applications', to='projects.project', verbose_name='projet')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_applications', to=settings.AUTH_USER_MODEL, verbose_name='étudiant')),
            ],
            options={
                'verbose_name': 'candidature',
                'verbose_name_plural': 'candidatures',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['status'], name='application_status_1508e0_idx'), models.Index(fields=['project', 'status'], name='application_project_f37dca_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'project'), name='uniq_student_application_per_project')],
            },
        ),
    ]
